### ISSUE TITLE
No way to easily access mangosd console

### ISSUE THREAD

**Issue by bstock84** [solipsist01/MangosZero#2]
I was not able to find a way to easily access mangosd console in order to setup accounts. I ended up doing the following:

1) Edit /config/wowconfig/mangosd.conf and set 
```
Console.Enable = 1
```

Note: This causes the daemon process to crash and re-launch repeatedly

2) Manually launch mangosd in order to get to the console
3) Once at the console, set your user to level 3
4) CTRL+C to exit, edit mangosd.conf and set:
```
Console.Enable = 0

Ra.Enable      = 1
Ra.IP          = 0.0.0.0
Ra.Port        = 3443
Ra.MinLevel    = 3
Ra.Secure      = 1
Ra.Stricted    = 0
```

5) Modify the container to include port 3443 (TCP) forwarding.

Now I am able to telnet on port 3443 to the host and create accounts, modify GM levels, etc.

**Comment by solipsist01** [comment]
When console is enabled, the process crashes constantly indeed, that's why i had it disabled :)
i have made adjustments to the container.
the RA port is now enabled, and i have changed the guide to reflect the changes.

This is the part of the guide:

# Remote Admin
You need to have a GM level 3 account to access the remote admin port.
Create one the following way.

```
docker exec -it vanilla /mangos/mangosd -c /config/wowconfig/console.conf
```

This will run a mangos config on another port with console enabled.
Essentially connecting you to the mangos console.
You can do this while your production mangos is running. 

Now create your GM account (or just elevate your current account)

```
account create gmadmin Y0UB4HDSTR0NGP4SSW0RD
account set gmlevel gmadmin 3
```

You can now connect with telnet to port 3443 with your gm account for abuse of GM power ;)

**Comment by solipsist01** [comment]
Turned out there was another bug.
When the container starts, it checks if there's a mangosd.conf and/or realmd.conf presence in /config/wowconfig

if not, it would copy a default mangosd.conf and realmd.conf. (with console disabled)
This didn't work, but now this is fixed.
It should copy console.conf as well if it doesn't exist

i'm rebuilding the image right now. will take 15 minutes.

**Comment by bstock84** [comment]
Awesome, thanks! I'm sure it will be helpful for others that aren't familiar with mangos.

Having that second conf file that lets you run another instance of mangosd is helpful, in fact I think that's going to be my preferred method of remote admin since I can use ssh instead of telnet. Is there any disadvantage to running the second mangosd instance vs telnetting into the first?

**Comment by solipsist01** [comment]
I'm not sure if it has a disadvantage.
You're essentially running another mangos instance alongside the currently live one.
I can imagine, that you can create new accounts etc, but cannot kick live players because they're running in the other instance. I'm not sure though :)

I assume this ticket is solved for you? :)

**Comment by bstock84** [comment]
This seems to be working great, thanks!
